/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: e34852120fca02556774764d3f6fd6fd)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	APP_TIME_ZONE: "Asia/Hong_Kong";
	ADMIN_USERNAME: "admin";
	AI_BASE_URL: "https://api.deepseek.com";
	AI_MODEL: "deepseek-chat";
}
declare namespace Cloudflare {
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "APP_TIME_ZONE" | "ADMIN_USERNAME" | "AI_BASE_URL" | "AI_MODEL">> {}
}
